# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    steps:
      - checkout
          
     # build the application image
     - run: docker-compose up -d tpisen

     # deploy the image
     - run: docker push tpisen:latest

     - run: docker push tpisen:$CIRCLE_BUILD_NUM